site_name: Mycel Manual
theme: material
nav:
  - Overview: index.md
  - Manual:
    - Scheduling algorithms: manual/scheduling-algorithms.md
  - Glossary: glossary.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
