site_name: Mycel Manual
theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.footer
    - navigation.indexes
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Overview: index.md
  - Implement Mycel:
    - Overview: implement/index.md
    - Prerequisites: implement/prerequisites.md
    - API Communication: implement/api-communication.md
    - Model Structuration: implement/model-structuration.md
    - Implementation Guides: implement/guides.md
    - Versioning: implement/versioning.md
    - Testing and Sharing: implement/testing-and-sharing.md
  - Contribution Guide: manual/contribution-guide.md
  - Learning Principles:
    - Scheduling algorithms: manual/scheduling-algorithms.md
  - Glossary: glossary.md
  - API Reference: api/index.md
repo_url: https://github.com/mycel-project/mycel
repo_name: mycel-project/mycel
edit_uri: https://github.com/mycel-project/mycel-project.github.io/edit/main/mycel-docs/docs/
extra:
  homepage: https://mycel-project.com/

markdown_extensions:
  - attr_list
  - md_in_html
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
        
plugins:
   - search
   - swagger-ui-tag:
       supportedSubmitMethods: []
